# Generated by Django 4.2.1 on 2023-12-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('mapping', models.JSONField()),
                ('moderation_results', models.JSONField(default=list)),
                ('current_node', models.CharField(max_length=32, verbose_name='当前节点')),
                ('conversation_id', models.CharField(max_length=32, verbose_name='对话ID')),
                ('system_id', models.CharField(max_length=32, verbose_name='首次对话ID')),
                ('messages', models.JSONField(default=list, verbose_name='对话列表')),
            ],
            options={
                'verbose_name': '对话',
                'verbose_name_plural': '对话',
            },
        ),
    ]
