# Generated by Django 4.2.1 on 2023-12-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatGPT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='mapping',
            field=models.JSONField(default=dict),
        ),
    ]
