# Generated by Django 4.2.1 on 2023-12-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatGPT', '0002_alter_conversation_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='current_node',
            field=models.CharField(max_length=100, verbose_name='当前节点'),
        ),
    ]
