# Generated by Django 4.2.1 on 2023-12-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatGPT', '0003_alter_conversation_current_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_id',
            field=models.CharField(max_length=100, verbose_name='对话ID'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='system_id',
            field=models.CharField(max_length=100, verbose_name='首次对话ID'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
    ]
